name: Deploy staging app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh command using ssh key
        uses: appleboy/ssh-action@v1
        with:
          host: 13.61.7.19
          username: ubuntu
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: | 
            cd home/ubuntu/turbo-app-class04
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart ft-server && pm2 restart https-server pm2 restart ws-server